language: android
jdk: oraclejdk8
dist: trusty
env:
global:
    - ANDROID_API_LEVEL=28
    - EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL